receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  debug:
    verbosity: detailed
  otlp:
    endpoint: 'jaeger:4317'
    tls:
      insecure: true
  prometheus:
    endpoint: '0.0.0.0:9464'
    namespace: default
  loki:
    endpoint: loki:3100/loki/api/v1/push
    tls:
      insecure: true

processors:
  batch:

service:
  pipelines:
    traces:
      receivers:
        - otlp
      exporters:
        - otlp
      processors:
        - batch
    metrics:
      receivers:
        - otlp
      exporters:
        - prometheus
      processors:
        - batch
    logs:
      receivers:
        - otlp
      exporters:
        - loki
        - debug
