include:
  - path: './.docker-compose/opentelemetry.compose.yml'
    service: opentelemetry
  - path: './.docker-compose/oracledb.compose.yml'
    service: oracledb
# services:
#   mongodb:
#     image: mongo:6.0.13
#     ports:
#       - '27017:27017'
#     volumes:
#       - mongodb-data:/data
#     restart: always

# volumes:
#   mongodb-data:
#     name: mongodb-data
