-- Materialised in-scope AHBRP query set for fixture verification.
-- Run as ahbrp/password@FREEPDB1. Each query is bracketed by a @@@<name>@@@
-- marker so the harness can split + sort per-query output for deterministic diffs.
-- Placeholders/binds from src/lib/db/queries/*.js are inlined here with
-- representative values (knex .toQuery() inlines IN-clause binds as quoted literals).
SET HEADING OFF
SET PAGESIZE 0
SET FEEDBACK OFF
SET VERIFY OFF
SET TRIMSPOOL ON
SET SQLBLANKLINES ON
SET LINESIZE 32767
SET LONG 100000
SET NULL <NULL>
SET COLSEP '|'
-- 'DD-MON-YYYY' parses the queries' literal date strings ('31-DEC-9999' and
-- '31/DEC/9999' — Oracle treats punctuation as interchangeable) and is
-- deterministic for output. Do NOT use 'YYYY-MM-DD' here: it makes those literal
-- comparisons raise ORA-01858 (the app relies on the DB's MON-style NLS).
ALTER SESSION SET NLS_LANGUAGE = 'AMERICAN';
ALTER SESSION SET NLS_DATE_FORMAT = 'DD-MON-YYYY';
ALTER SESSION SET NLS_TIMESTAMP_FORMAT = 'DD-MON-YYYY HH24:MI:SS';

PROMPT @@@find-holdings@@@
WITH
TARGET_CPH AS (
  SELECT CPH.CPH, CPH.CPH_TYPE, SUBSTR(CPH.CPH, 1, 6) AS COUNTY_PARISH_CODE
  FROM AHBRP.CPH
  WHERE CPH.CPH IN ('11/111/1111','22/222/2222','33/333/3333','04/432/1234','45/001/0002','01/409/1111','98/001/0001','98/002/0001','99/999/9999','01/001/0001')
),
ACTIVE_HOLDERSHIP AS (
  SELECT TC.CPH, TC.CPH_TYPE, TC.COUNTY_PARISH_CODE, L.LOCATION_ID, P.PARTY_ID
  FROM TARGET_CPH TC
  JOIN AHBRP.FEATURE_INVOLVEMENT FI ON FI.CPH = TC.CPH
  JOIN AHBRP.LOCATION L ON L.FEATURE_PK = FI.FEATURE_PK
  JOIN AHBRP.FEATURE_STATE FS ON FS.FEATURE_PK = FI.FEATURE_PK
  JOIN AHBRP.PARTY_ROLE PR ON PR.PARTY_ROLE_PK = FI.PARTY_ROLE_PK
  JOIN AHBRP.PARTY P ON P.PARTY_PK = PR.PARTY_PK
  JOIN AHBRP.PARTY_STATE PS ON PS.PARTY_PK = P.PARTY_PK
  WHERE FI.FEATURE_INVOLVEMENT_TYPE = 'CPHHOLDERSHIP'
    AND FI.FEATURE_INVOLV_TO_DATE IS NULL
    AND FS.FEATURE_STATUS_CODE <> 'INACTIVE'
    AND FS.FEATURE_STATE_TO_DTTM IS NULL
    AND PR.PARTY_ROLE_TO_DATE IS NULL
    AND PS.PARTY_STATUS_CODE <> 'INACTIVE'
    AND PS.PARTY_STATE_TO_DTTM IS NULL
),
LOCAL_AUTHORITY AS (
  SELECT RDCD.SHORT_DESCRIPTION AS LA_NAME, RDC.CODE AS LA_NUMBER, RDC1.CODE AS COUNTY_PARISH_CODE
  FROM AHBRP.REF_DATA_SET_MAP RDSM
  JOIN AHBRP.REF_DATA_CODE_MAP RDCM ON RDSM.REF_DATA_SET_MAP_PK = RDCM.REF_DATA_SET_MAP_PK
  JOIN AHBRP.REF_DATA_CODE RDC ON RDCM.FROM_REF_DATA_CODE_PK = RDC.REF_DATA_CODE_PK
  JOIN AHBRP.REF_DATA_CODE RDC1 ON RDCM.TO_REF_DATA_CODE_PK = RDC1.REF_DATA_CODE_PK
  JOIN AHBRP.REF_DATA_CODE_DESC RDCD ON RDC.REF_DATA_CODE_PK = RDCD.REF_DATA_CODE_PK
  WHERE RDSM.REF_DATA_SET_MAP_NAME = 'LOCAL_AUTHORITY_COUNTY_PARISH'
    AND RDSM.EFFECTIVE_TO_DATE = '31/DEC/9999'
    AND RDCM.EFFECTIVE_TO_DATE = '31/DEC/9999'
    AND RDC.EFFECTIVE_TO_DATE = '31/DEC/9999'
    AND RDC1.EFFECTIVE_TO_DATE = '31/DEC/9999'
)
SELECT DISTINCT AH.CPH AS CPH_ID, 'ACTIVE' AS CPH_HOLDERSHIP_ACTIVE, AH.CPH_TYPE,
  LA.LA_NAME, LA.LA_NUMBER, AH.LOCATION_ID, AH.PARTY_ID
FROM ACTIVE_HOLDERSHIP AH
LEFT JOIN LOCAL_AUTHORITY LA ON AH.COUNTY_PARISH_CODE = LA.COUNTY_PARISH_CODE;

PROMPT @@@get-units@@@
SELECT cph, location_id, feature_name, main_role_type, person_family_name,
  person_given_name, organisation_name, party_id, asset_id, asset_location_type,
  asset_type, animal_species_code, animal_group_id_mch_ext_ref,
  animal_group_id_mch_frm_dat, animal_group_id_mch_to_dat,
  animal_production_usage_code, asset_involvement_type, cph_type, herdmark,
  keeper_of_unit, property_number, postcode, owner_of_unit
FROM ahbrp.v_cph_customer_unit
WHERE cph LIKE '04/432/1234';

PROMPT @@@get-purpose-species@@@
SELECT SHORT_DESCRIPTION PURPOSE_SPECIES_DESC, CODE PURPOSE_SPECIES_CODE
FROM AHBRP.REF_DATA_SET, AHBRP.REF_DATA_CODE, AHBRP.REF_DATA_CODE_DESC
WHERE CODE IN ('Cattle','Sheep','Mixed','Pigs')
  AND REF_DATA_SET_NAME = 'BCF_ANIMAL_SPECIES'
  AND REF_DATA_SET.EFFECTIVE_TO_DATE IS NULL
  AND REF_DATA_SET.REF_DATA_SET_PK = REF_DATA_CODE.REF_DATA_SET_PK
  AND REF_DATA_CODE.EFFECTIVE_TO_DATE = '31-DEC-9999'
  AND REF_DATA_CODE.REF_DATA_CODE_PK = REF_DATA_CODE_DESC.REF_DATA_CODE_PK
  AND LANGUAGE_CODE = 'ENG';

PROMPT @@@get-workarea@@@
SELECT SHORT_DESCRIPTION WORK_AREA_DESC, CODE WORK_AREA_CODE
FROM AHBRP.REF_DATA_SET, AHBRP.REF_DATA_CODE, AHBRP.REF_DATA_CODE_DESC
WHERE CODE IN ('Tuberculosis','General Inspection','Disease Investigation','Movement Controls','Exotic Disease','Biosecurity Audit')
  AND REF_DATA_SET_NAME = 'WORK_AREA'
  AND REF_DATA_SET.EFFECTIVE_TO_DATE IS NULL
  AND REF_DATA_SET.REF_DATA_SET_PK = REF_DATA_CODE.REF_DATA_SET_PK
  AND REF_DATA_CODE.EFFECTIVE_TO_DATE = '31-DEC-9999'
  AND REF_DATA_CODE.REF_DATA_CODE_PK = REF_DATA_CODE_DESC.REF_DATA_CODE_PK
  AND LANGUAGE_CODE = 'ENG';

PROMPT @@@get-customer-types@@@
WITH target_party AS (
  SELECT p.party_pk, p.party_id FROM ahbrp.party p
  JOIN ahbrp.party_state ps ON ps.party_pk = p.party_pk
  WHERE ps.party_status_code <> 'INACTIVE' AND ps.party_state_to_dttm IS NULL
    AND p.party_id IN ('C123456','C234567','O123456')
),
customer_type_candidates AS (
  SELECT tp.party_pk, 'PERSON' AS customer_type, 1 AS type_priority
  FROM target_party tp
  JOIN ahbrp.party_version pv ON pv.party_pk = tp.party_pk AND pv.party_type = 'PERSON' AND pv.party_version_to_datetime = '31-DEC-9999'
  JOIN ahbrp.person pe ON pe.party_pk = tp.party_pk
  UNION ALL
  SELECT tp.party_pk, 'ORGANISATION' AS customer_type, 2 AS type_priority
  FROM target_party tp
  JOIN ahbrp.party_version pv ON pv.party_pk = tp.party_pk AND pv.party_type = 'ORGANISATION' AND pv.party_version_to_datetime = '31-DEC-9999'
  JOIN ahbrp.organisation o ON o.party_pk = tp.party_pk
),
customer_type_by_party AS (
  SELECT ctc.party_pk, MAX(ctc.customer_type) KEEP (DENSE_RANK FIRST ORDER BY ctc.type_priority) AS customer_type
  FROM customer_type_candidates ctc GROUP BY ctc.party_pk
)
SELECT tp.party_id AS customer_id, ctbp.customer_type
FROM target_party tp
JOIN customer_type_by_party ctbp ON ctbp.party_pk = tp.party_pk;

PROMPT @@@find-holding-04432@@@
WITH
TARGET_CPH AS (
  SELECT CPH.CPH, CPH.CPH_TYPE, SUBSTR(CPH.CPH, 1, 6) AS COUNTY_PARISH_CODE
  FROM AHBRP.CPH WHERE CPH.CPH = '04/432/1234'
),
ACTIVE_HOLDERSHIP AS (
  SELECT TC.CPH, TC.CPH_TYPE, TC.COUNTY_PARISH_CODE, L.LOCATION_ID, P.PARTY_ID
  FROM TARGET_CPH TC
  JOIN AHBRP.FEATURE_INVOLVEMENT FI ON FI.CPH = TC.CPH
  JOIN AHBRP.LOCATION L ON L.FEATURE_PK = FI.FEATURE_PK
  JOIN AHBRP.FEATURE_STATE FS ON FS.FEATURE_PK = FI.FEATURE_PK
  JOIN AHBRP.PARTY_ROLE PR ON PR.PARTY_ROLE_PK = FI.PARTY_ROLE_PK
  JOIN AHBRP.PARTY P ON P.PARTY_PK = PR.PARTY_PK
  JOIN AHBRP.PARTY_STATE PS ON PS.PARTY_PK = P.PARTY_PK
  WHERE FI.FEATURE_INVOLVEMENT_TYPE = 'CPHHOLDERSHIP' AND FI.FEATURE_INVOLV_TO_DATE IS NULL
    AND FS.FEATURE_STATUS_CODE <> 'INACTIVE' AND FS.FEATURE_STATE_TO_DTTM IS NULL
    AND PR.PARTY_ROLE_TO_DATE IS NULL AND PS.PARTY_STATUS_CODE <> 'INACTIVE' AND PS.PARTY_STATE_TO_DTTM IS NULL
),
LOCAL_AUTHORITY AS (
  SELECT RDCD.SHORT_DESCRIPTION AS LA_NAME, RDC.CODE AS LA_NUMBER, RDC1.CODE AS COUNTY_PARISH_CODE
  FROM AHBRP.REF_DATA_SET_MAP RDSM
  JOIN AHBRP.REF_DATA_CODE_MAP RDCM ON RDSM.REF_DATA_SET_MAP_PK = RDCM.REF_DATA_SET_MAP_PK
  JOIN AHBRP.REF_DATA_CODE RDC ON RDCM.FROM_REF_DATA_CODE_PK = RDC.REF_DATA_CODE_PK
  JOIN AHBRP.REF_DATA_CODE RDC1 ON RDCM.TO_REF_DATA_CODE_PK = RDC1.REF_DATA_CODE_PK
  JOIN AHBRP.REF_DATA_CODE_DESC RDCD ON RDC.REF_DATA_CODE_PK = RDCD.REF_DATA_CODE_PK
  WHERE RDSM.REF_DATA_SET_MAP_NAME = 'LOCAL_AUTHORITY_COUNTY_PARISH'
    AND RDSM.EFFECTIVE_TO_DATE = '31/DEC/9999' AND RDCM.EFFECTIVE_TO_DATE = '31/DEC/9999'
    AND RDC.EFFECTIVE_TO_DATE = '31/DEC/9999' AND RDC1.EFFECTIVE_TO_DATE = '31/DEC/9999'
)
SELECT AH.CPH AS cph, 'Y' AS cphactive, AH.CPH_TYPE AS cphtype, AH.PARTY_ID AS cphholdercustomerid,
  AH.LOCATION_ID AS locationid, LA.LA_NAME AS laname, LA.LA_NUMBER AS lanumber
FROM ACTIVE_HOLDERSHIP AH LEFT JOIN LOCAL_AUTHORITY LA ON AH.COUNTY_PARISH_CODE = LA.COUNTY_PARISH_CODE;

PROMPT @@@find-customers-PERSON@@@
@@scripts/verify/find-customers-PERSON.sql

PROMPT @@@find-customers-ORGANISATION@@@
@@scripts/verify/find-customers-ORGANISATION.sql

PROMPT @@@find-locations@@@
@@scripts/verify/find-locations.sql

PROMPT @@@get-location-L98001@@@
@@scripts/verify/get-location-L98001.sql

PROMPT @@@get-location-L97339@@@
@@scripts/verify/get-location-L97339.sql

PROMPT @@@DONE@@@
EXIT
