services:
  oracledb:
    image: container-registry.oracle.com/database/free:latest
    ports:
      - '1521:1521'
      - '5500:5500'
    environment:
      - ORACLE_PW="letmein"
    volumes:
      - ./oracledb:/opt/oracle/scripts/startup
      - oracledb-data:/opt/oracle/oradata
    restart: always

volumes:
  oracledb-data:
    name: oracledb-data-v2
