services:
  oracledb:
    image: container-registry.oracle.com/database/free:23.8.0.0
    ports:
      - '1521:1521'
      - '5500:5500'
    volumes:
      - ./oracledb:/opt/oracle/scripts/startup
    restart: always
