SELECT
LOCATION_ID,
PAON_START_NUMBER paon_start_number,
PAON_START_NUMBER_SUFFIX paon_start_number_suffix,
PAON_END_NUMBER paon_end_number,
PAON_END_NUMBER_SUFFIX paon_end_number_suffix,
PAON_DESCRIPTION paon_description,
SAON_DESCRIPTION saon_description,
SAON_START_NUMBER saon_start_number,
SAON_START_NUMBER_SUFFIX saon_start_number_suffix,
SAON_END_NUMBER saon_end_number,
SAON_END_NUMBER_SUFFIX saon_end_number_suffix,
STREET,
LOCALITY,
TOWN,
ADMINISTRATIVE_AREA COUNTY,
POSTCODE,
UK_INTERNAL_CODE uk_internal_code,
COUNTRY_CODE country_code,
UNIT_ID unit_id,
'LU' unit_type,
OS_MAP_REFERENCE os_map_reference,
USUAL_QUANTITY_OF_ANIMALS usual_quantity_of_animals

FROM
AHBRP.LOCATION,
AHBRP.FEATURE_ADDRESS FA,
AHBRP.FEATURE_STATE FS,
AHBRP.BS7666_ADDRESS BA,
AHBRP.ASSET_LOCATION AL,
AHBRP.LIVESTOCK_UNIT LU,
AHBRP.ASSET_STATE ASS,
AHBRP.FEATURE_POINT FP,
AHBRP.ASSET,
AHBRP.COLL_REGSTRD_ANIMAL_GROUP COLL

WHERE
LOCATION.FEATURE_PK = FA.FEATURE_PK(+)
AND
LOCATION.FEATURE_PK = FS.FEATURE_PK
AND
FA.ADDRESS_PK = BA.ADDRESS_PK(+)
AND
LOCATION.FEATURE_PK = AL.FEATURE_PK
AND
AL.ASSET_PK = LU.ASSET_PK
AND
LU.ASSET_PK = ASS.ASSET_PK
AND
FA.FEATURE_ADDRESS_TO_DATE(+) IS NULL
AND
AL.ASSET_LOCATION_TO_DATE IS NULL
AND
AL.ASSET_LOCATION_TYPE ='PRIMARYLOCATION'
AND
ASS.ASSET_STATUS_CODE <> 'INACTIVE'
AND
ASS.ASSET_STATE_TO_DTTM IS NULL
AND
FS.FEATURE_STATUS_CODE <> 'INACTIVE'
AND
FS.FEATURE_STATE_TO_DTTM IS NULL
AND
LOCATION.FEATURE_PK=FP.FEATURE_PK(+)
AND
PRIMARY_FEATURE_POINT_IND(+)='Y'
AND
FEATURE_POINT_TO_DATE(+) IS NULL
AND
LU.ASSET_PK=ASSET.ASSET_PK(+)
AND
ASSET.ANIMAL_PK=COLL.ANIMAL_PK(+)
AND
LOCATION.LOCATION_ID IN (:locationIds)

UNION

SELECT
LOCATION_ID,
PAON_START_NUMBER paon_start_number,
PAON_START_NUMBER_SUFFIX paon_start_number_suffix,
PAON_END_NUMBER paon_end_number,
PAON_END_NUMBER_SUFFIX paon_end_number_suffix,
PAON_DESCRIPTION paon_description,
SAON_DESCRIPTION saon_description,
SAON_START_NUMBER saon_start_number,
SAON_START_NUMBER_SUFFIX saon_start_number_suffix,
SAON_END_NUMBER saon_end_number,
SAON_END_NUMBER_SUFFIX saon_end_number_suffix,
STREET,
LOCALITY,
TOWN,
ADMINISTRATIVE_AREA COUNTY,
POSTCODE,
UK_INTERNAL_CODE uk_internal_code,
COUNTRY_CODE country_code,
UNIT_ID unit_id,
'F' unit_type,
OS_MAP_REFERENCE os_map_reference,
USUAL_QUANTITY_OF_ANIMALS usual_quantity_of_animals

FROM
AHBRP.LOCATION,
AHBRP.FEATURE_ADDRESS FA,
AHBRP.FEATURE_STATE FS,
AHBRP.BS7666_ADDRESS BA,
AHBRP.ASSET_LOCATION AL,
AHBRP.FACILITY,
AHBRP.ASSET_STATE ASS,
AHBRP.FEATURE_POINT FP,
AHBRP.ASSET,
AHBRP.COLL_REGSTRD_ANIMAL_GROUP COLL

WHERE
LOCATION.FEATURE_PK = FA.FEATURE_PK(+)
AND
LOCATION.FEATURE_PK = FS.FEATURE_PK
AND
FA.ADDRESS_PK = BA.ADDRESS_PK(+)
AND
LOCATION.FEATURE_PK = AL.FEATURE_PK
AND
AL.ASSET_PK = FACILITY.ASSET_PK
AND
FACILITY.ASSET_PK = ASS.ASSET_PK
AND
FA.FEATURE_ADDRESS_TO_DATE(+) IS NULL
AND
AL.ASSET_LOCATION_TO_DATE IS NULL
AND
AL.ASSET_LOCATION_TYPE='PRIMARYLOCATION'
AND
ASS.ASSET_STATUS_CODE<> 'INACTIVE'
AND
ASS.ASSET_STATE_TO_DTTM IS NULL
AND
FS.FEATURE_STATUS_CODE <> 'INACTIVE'
AND
FS.FEATURE_STATE_TO_DTTM IS NULL
AND
LOCATION.FEATURE_PK=FP.FEATURE_PK(+)
AND
PRIMARY_FEATURE_POINT_IND(+)='Y'
AND
FEATURE_POINT_TO_DATE(+) IS NULL
AND
FACILITY.ASSET_PK=ASSET.ASSET_PK(+)
AND
ASSET.ANIMAL_PK=COLL.ANIMAL_PK(+)
AND
LOCATION.LOCATION_ID IN (:locationIds)
