SELECT
CPH.CPH cph,
'Y' cphactive, 
CPH_TYPE cphtype,
PARTY_ID cphholdercustomerid,
LOCATION_ID locationid,
ref_data_code_desc.short_Description laname,
ref_data_Code.code lanumber

FROM
AHBRP.CPH,
AHBRP.FEATURE_INVOLVEMENT FI,
AHBRP.LOCATION,
AHBRP.FEATURE_STATE FS,
AHBRP.PARTY_ROLE PR,
AHBRP.PARTY,
AHBRP.PARTY_STATE PS,
AHBRP.ref_data_Set_map,
AHBRP.ref_data_code_map,
AHBRP.ref_data_code,
AHBRP.ref_data_code ref_data_code_1,
AHBRP.ref_data_Code_desc

WHERE
CPH.CPH = FI.CPH
AND
FI.FEATURE_PK = LOCATION.FEATURE_PK
AND
FI.FEATURE_PK = FS.FEATURE_PK
AND
FI.FEATURE_INVOLVEMENT_TYPE = 'CPHHOLDERSHIP'
AND
FI.FEATURE_INVOLV_TO_DATE IS NULL
AND
FS.FEATURE_STATUS_CODE <> 'INACTIVE'
AND
FS.FEATURE_STATE_TO_DTTM IS NULL
AND
FI.PARTY_ROLE_PK = PR.PARTY_ROLE_PK
AND
PR.PARTY_PK = PARTY.PARTY_PK
AND 
PR.PARTY_ROLE_TO_DATE IS NULL
AND
PARTY.PARTY_PK = PS.PARTY_PK
AND
PS.PARTY_STATUS_CODE <> 'INACTIVE'
AND 
PS.PARTY_STATE_TO_DTTM IS NOT NULL
AND
REF_DATA_SET_MAP.REF_DATA_SET_MAP_PK = REF_DATA_CODE_MAP.REF_DATA_SET_MAP_PK
and 
REF_DATA_SET_MAP.EFFECTIVE_TO_DATE = '31/DEC/9999'
AND 
REF_DATA_SET_MAP.REF_DATA_SET_MAP_NAME = 'LOCAL_AUTHORITY_COUNTY_PARISH'
AND
REF_DATA_CODE_MAP.FROM_REF_DATA_CODE_PK = REF_DATA_CODE.REF_DATA_CODE_PK
and 
REF_DATA_CODE_MAP.EFFECTIVE_TO_DATE = '31/DEC/9999'
AND 
REF_DATA_CODE.REF_DATA_CODE_PK = REF_DATA_CODE_DESC.REF_DATA_CODE_PK
AND 
REF_DATA_CODE.EFFECTIVE_TO_DATE= '31/DEC/9999'
and 
REF_DATA_CODE_MAP.TO_REF_DATA_CODE_PK = REF_DATA_CODE_1.REF_DATA_CODE_PK
and 
REF_DATA_CODE_1.EFFECTIVE_TO_DATE = '31/DEC/9999'
AND
SUBSTR(CPH.CPH,1,6) = REF_DATA_CODE_1.CODE
AND
CPH.CPH = :cph