SELECT
  SHORT_DESCRIPTION WORK_AREA_DESC,
  CODE WORK_AREA_CODE
FROM
  AHBRP.REF_DATA_SET,
  AHBRP.REF_DATA_CODE,
  AHBRP.REF_DATA_CODE_DESC
WHERE
  CODE IN (__WORKAREA_CODES__)
  AND
  REF_DATA_SET_NAME= 'WORK_AREA'
  AND
  REF_DATA_SET.EFFECTIVE_TO_DATE IS NULL
  AND
  REF_DATA_SET.REF_DATA_SET_PK=REF_DATA_CODE.REF_DATA_SET_PK
  AND
  REF_DATA_CODE.EFFECTIVE_TO_DATE = '31-DEC-9999'
  AND
  REF_DATA_CODE.REF_DATA_CODE_PK=REF_DATA_CODE_DESC.REF_DATA_CODE_PK
  AND
  LANGUAGE_CODE='ENG'
