SELECT
LOCATION_ID,
PAON_START_NUMBER paonstartnumber,
PAON_START_NUMBER_SUFFIX paonstartnumbersuffix,
PAON_END_NUMBER paonendnumber,
PAON_END_NUMBER_SUFFIX paonendnumbersuffix,
PAON_DESCRIPTION paondescription,
SAON_DESCRIPTION saondescription,
SAON_START_NUMBER saonstartnumber,
SAON_START_NUMBER_SUFFIX saonstartnumbersuffix,
SAON_END_NUMBER saonendnumber,
SAON_END_NUMBER_SUFFIX saonendnumbersuffix,
STREET,
LOCALITY,
TOWN,
ADMINISTRATIVE_AREA COUNTY,
POSTCODE,
UK_INTERNAL_CODE ukinternalcode,
COUNTRY_CODE countrycode,
UNIT_ID unitid,
'LU' unittype

FROM
AHBRP.LOCATION,
AHBRP.FEATURE_ADDRESS FA,
AHBRP.FEATURE_STATE FS,
AHBRP.BS7666_ADDRESS BA,
AHBRP.ASSET_LOCATION AL,
AHBRP.LIVESTOCK_UNIT LU,
AHBRP.ASSET_STATE ASS

WHERE
LOCATION.FEATURE_PK = FA.FEATURE_PK
AND 
LOCATION.FEATURE_PK = FS.FEATURE_PK
AND
FA.ADDRESS_PK = BA.ADDRESS_PK
AND
LOCATION.FEATURE_PK = AL.FEATURE_PK
AND
AL.ASSET_PK = LU.ASSET_PK
AND
LU.ASSET_PK = ASS.ASSET_PK
AND
FA.FEATURE_ADDRESS_TO_DATE IS NULL
AND
AL.ASSET_LOCATION_TO_DATE IS NULL
AND
AL.ASSET_LOCATION_TYPE ='PRIMARYLOCATION'
AND
ASS.ASSET_STATUS_CODE <> 'INACTIVE'
AND
ASS.ASSET_STATE_TO_DTTM IS NULL
AND
FS.FEATURE_STATUS_CODE <> 'INACTIVE'
AND 
FS.FEATURE_STATE_TO_DTTM IS NULL
AND
LOCATION.LOCATION_ID ='L97339'

union

SELECT
LOCATION_ID,
PAON_START_NUMBER,
PAON_START_NUMBER_SUFFIX,
PAON_END_NUMBER,
PAON_END_NUMBER_SUFFIX,
PAON_DESCRIPTION,
SAON_DESCRIPTION,
SAON_START_NUMBER,
SAON_START_NUMBER_SUFFIX,
SAON_END_NUMBER,
SAON_END_NUMBER_SUFFIX,
STREET,
LOCALITY,
TOWN,
ADMINISTRATIVE_AREA COUNTY,
POSTCODE,
UK_INTERNAL_CODE,
COUNTRY_CODE,
UNIT_ID,
'F' UNIT_TYPE

FROM
AHBRP.LOCATION,
AHBRP.FEATURE_ADDRESS FA,
AHBRP.FEATURE_STATE FS,
AHBRP.BS7666_ADDRESS BA,
AHBRP.ASSET_LOCATION AL,
AHBRP.FACILITY,
AHBRP.ASSET_STATE ASS

WHERE
LOCATION.FEATURE_PK = FA.FEATURE_PK
AND 
LOCATION.FEATURE_PK = FS.FEATURE_PK
AND
FA.ADDRESS_PK = BA.ADDRESS_PK
AND
LOCATION.FEATURE_PK = AL.FEATURE_PK
AND
AL.ASSET_PK = FACILITY.ASSET_PK
AND
FACILITY.ASSET_PK = ASS.ASSET_PK
AND
FA.FEATURE_ADDRESS_TO_DATE IS NULL
AND
AL.ASSET_LOCATION_TO_DATE IS NULL
AND
AL.ASSET_LOCATION_TYPE='PRIMARYLOCATION'
AND
ASS.ASSET_STATUS_CODE<> 'INACTIVE'
AND
ASS.ASSET_STATE_TO_DTTM IS NULL
AND
FS.FEATURE_STATUS_CODE <> 'INACTIVE'
AND
FS.FEATURE_STATE_TO_DTTM IS NULL
AND
LOCATION.LOCATION_ID= :location
