name: Check Pull Request

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - edited
      - reopened
      - synchronize
      - ready_for_review

jobs:
  pr-validator:
    name: Run Pull Request Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test code and Create Test Coverage Reports
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm

      - name: Install Oracle Instant Client
        id: oracle
        run: ./.github/scripts/oracle-instant-client.sh

      - name: Login to oracle container registry
        uses: docker/login-action@v3
        with:
          registry: container-registry.oracle.com
          username: ${{ secrets.ORACLE_USERNAME }}
          password: ${{ secrets.ORACLE_SECRET_KEY }}

      - name: Docker pull Oracle DB
        run: docker pull container-registry.oracle.com/database/free:latest

      - run: npm i

      - run: npm run format:check

      - run: npm run lint

      - run: npm test
        env:
          ORACLE_CLIENT_LIB_DIR: ${{ steps.oracle.outputs.install-path }}
          DEBUG: testcontainers

      - name: Free disk space (Docker and node_modules)
        if: always()
        run: |
          echo "Stopping and removing all containers..."
          docker ps -aq | xargs -r docker rm -f || true
          echo "Removing all Docker images..."
          docker images -aq | xargs -r docker rmi -f || true
          echo "Pruning builder cache..."
          docker builder prune -af || true
          echo "Pruning system (networks/volumes)..."
          docker system prune -af --volumes || true
          echo "Removing node_modules to free space..."
          rm -rf node_modules || true
          echo "Disk usage after cleanup:"
          df -h

      - name: Test Docker Image Build
        run: |
          set +e
          docker build --no-cache --tag cdp-node-backend-template .
          exit $?

#      - name: SonarCloud Scan
#        if: github.actor != 'dependabot[bot]'
#        uses: SonarSource/sonarcloud-github-action@master
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
